networks:
  ai4industry:
    name: ai4ind-ufsc_ai4industry
    external: true

services:
  bob:
    image: jomifred/jacamo:1.2
    command: kg.jcm
    ports:
      - 3274:3272
      - 3275:3273
    networks:
      - ai4industry
    volumes:
      - ../wot/gradle-cache:/root/.gradle
      - .:/app
    working_dir: /app
